### PR TITLE
app.py add host

### PR DESCRIPTION
**Pull request by brionychiu**
小丑魚
[http://54.198.160.161:3000/api/attractions?page=0&keyword=溫泉](http://54.198.160.161:3000/api/attractions?page=0&keyword=%E6%BA%AB%E6%B3%89)
http://54.198.160.161:3000/api/attractions?page=4
http://54.198.160.161:3000/api/attractions/12

### CODE REVIEW

**Comment by cwpeng** [comment]
Your online URLs are broken. Try to find cause, fix it, and ask me to review again.

**Comment by brionychiu** [comment]
問題已解決，因為app.py中沒有把connection_pool的連線歸還，所以加入close程式，請彭彭老師再審閱，謝謝。

**Review by cwpeng — CHANGES_REQUESTED** [review]
Almost done, but response data structure of http://54.198.160.161:3000/api/attractions/12 is not correct, check API spec carefully.

Fix it, create new commit, and ask me to review again.

**Comment by brionychiu** [comment]
小丑魚
fix data structure correct
http://54.198.160.161:3000/api/attractions?page=0&keyword=溫泉
http://54.198.160.161:3000/api/attractions?page=4
http://54.198.160.161:3000/api/attraction/12

**Comment by cwpeng** [comment]
Looks OK, but your server is broken when I test twice. I guess it's due to database connection loss. Fix it and leave comment for me to review again.

**Comment by brionychiu** [comment]
already fix~ due to con-close didn't set on api/attration/id code

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
