### PR TITLE
Develop-3

### PR DESCRIPTION
**Pull request by brionychiu**
Discord : 小丑魚
http://54.198.160.161:3000/
http://54.198.160.161:3000/attraction/22

thank you~

### CODE REVIEW

**Comment by cwpeng** [comment]
Aspect ratio (長寬比) of images should always the same with original ones.

未命名-2

**Comment by brionychiu** [comment]
fix already

**Comment by brionychiu** [comment]
Discord : 小丑魚
http://54.198.160.161:3000/
http://54.198.160.161:3000/attraction/22
i commited attraction.css file , but not show on github..
image

**Comment by brionychiu** [comment]
can check on the following link
[modified pic ratio](https://github.com/brionychiu/Origin-Repository/commit/62422b2b5fb20b0c66ee2854e9ac2ff19558f778 )

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
